
name: Run COBOL Program (from main, building master)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: List files (diagnóstico)
        run: ls -R

      - name: Install GnuCOBOL
        run: |
          sudo apt-get update
          sudo apt-get install -y gnucobol

      - name: Compile COBOL program
        # Se o arquivo está na raiz da master:
        run: cobc -x "02_Add.cob" -o "02_Add"

      - name: Execute COBOL program
        run: ./02_Add
